
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT_HOLDER_NAME TEXT NOT NULL,
    ACCOUNT_NUMBER TEXT NOT NULL,
    ACCOUNT_TYPE TEXT NOT NULL,
    ACCOUNT_BALANCE INTEGER NOT NULL,
    ACCOUNT_STATUS TEXT NOT NULL,
    ACCOUNT_CREATED_DATE DATETIME NOT NULL,
    ACCOUNT_UPDATED_DATE DATETIME NOT NULL
);
